<testsuite name="HybridAppDemoFeature.Hybrid App Demo" tests="2" errors="1" failures="0" skipped="0" time="14.018144"><testcase classname="HybridAppDemoFeature.Hybrid App Demo" name="Test the search box" status="passed" time="12.022431"><system-out>
<![CDATA[
@scenario.begin
  Scenario: Test the search box
    Given I launched the mobile native chrome app ... passed in 0.000s
    When I am clicking on search and pass values to search ... passed in 8.292s
    Then I Search for the text ... passed in 3.731s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase><testcase classname="HybridAppDemoFeature.Hybrid App Demo" name="Click on the link" status="failed" time="1.995714"><error type="WebDriverException" message="Message: An unknown server-side error occurred while processing the command. Ori...">
<![CDATA[
Failing step: When I test the web_view ... failed in 1.996s
Location: features\HybridAppDemoFeature.feature:9
Traceback (most recent call last):
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\behave\model.py", line 1456, in run
    match.run(runner.context)
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\behave\model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features\steps\HybridAppDemoSteps.py", line 27, in switching_view
    context.feature.hybridApp_demo.switching_view("WEBVIEW_chrome")
  File "C:\Users\saktivel.rajasekar\Desktop\Appium Core freamework\Python_Automation%20Framework\Shell_FE_Behave_Tests\MobileApplicationLibrary\FunctionalLibrary\HybridAppDemoFunctions.py", line 39, in switching_view
    AndroidUtilities.switch_context(context_value)
  File "C:\Users\saktivel.rajasekar\Desktop\Appium Core freamework\Python_Automation%20Framework\Shell_FE_Appium_Core\Utilities\AndroidUtilities.py", line 248, in switch_context
    AppiumBase.driver.switch_to.context(switch_view)
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\appium\webdriver\switch_to.py", line 35, in context
    self._driver.execute(MobileCommand.SWITCH_TO_CONTEXT, {'name': context_name})
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "c:\users\saktivel.rajasekar\desktop\appium core freamework\python_automation%20framework\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*14061
  (make sure the app has its WebView/WebLayer configured for debugging)


Captured stdout:
APPview : NATIVE_APP

Captured logging:
INFO:AndroidUtilities:Current context of the is NATIVE_APP.]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Click on the link
    When I test the web_view ... failed in 1.996s
    Then I replace the search text ... skipped in 0.000s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
APPview : NATIVE_APP

]]>
</system-out></testcase></testsuite>